project:
  type: website
  output-dir: docs

website:
  title: "ACT SAT Summer Class"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ACT_Resources_Free.qmd
      - ACT_Resources_Paid.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



