---
title: "ACT Resources Free"
editor: visual
---

### Overall

1.  [List of every ACT test](https://mcelroytutoring.com/lower.php?url=44-official-sat-pdfs-and-82-official-act-pdf-practice-tests-free)

2.  [Every ACT answer key](https://www.prepsharp.com/act-answer-keys/)

3.  [Brilliant Prep Your-sat-act-study-plan](https://learn.brilliantprep.com/p/your-sat-act-study-plan)

4.  [mcelroy  tutoring ACT action plan](https://www.mcelroytutoring.com/blog-post.php?id=1402&title=ACT+Action+Plan%3A+How+to+Study+and+Prepare+for+the+ACT+College+Entrance+Exam)

The biggest resource is access to real ACT past tests ([List of every ACT test](https://mcelroytutoring.com/lower.php?url=44-official-sat-pdfs-and-82-official-act-pdf-practice-tests-free)). You need access to a printer to use these. Alternatively you can buy the red book (the official ACT guide) which has 6 tests.

You want to about 50% of your study time doing timed practice test sections (one of English, Math, Reading & Science). You don't have to do full tests but you must always time yourself for every section.

The prepsharp website ([Every ACT answer key](https://www.prepsharp.com/act-answer-keys/)) and APP provides answers to every ACT test. It also provides bubble sheets that can be printed and virtual proctors so you can do tests in real conditions. After completing a test you must record your result. To do this you can use the google sheet provided by [Brilliant Prep Your-sat-act-study-plan](https://learn.brilliantprep.com/p/your-sat-act-study-plan). You want a record of every question you did not know how to do and go back over them from time-to-time.

### English

1.  <https://blog.prepscholar.com/the-complete-guide-to-act-grammar-rules>

2.  [Free Virtual ACT English Lesson \-- Covering the Most Important ACT English Grammar Concepts!](https://www.youtube.com/watch?v=aG1iEjVZyZY)

3.  <https://thecriticalreader.com/complete-sat-grammar-rules/>

English is often seen as the easiest section of the ACT. The timing is not as tough as the other sections. Most of the test is on grammar rules (identifying the need for corrections in the passage). Some of the test is on style. The amount you need to learn is much less than math (the other section where you really need to learn things). The links above provide grammar guides. Potentially this is all you need to learn. By going through practice tests and identifying your mistakes you will improve. There is not too much strategy to boost your score but generally you answer questions as you go along rather than reading the whole passage.

### Math

1.  [The 52 ACT Math Skills](https://www.youtube.com/playlist?list=PL2AoJMrlAorzqxnsyxAyCrtPjYpTdUiTt)

2.  [Reason Prep ACT-Math-Gauntlet](https://www.scribd.com/document/412819316/ACT-Math-Gauntlet)

3.  [ACT Math Prep Playlist](https://www.youtube.com/playlist?list=PL2ix4u6yN0jJJGYr0zQVsXY0JozcIDWP9)

4.  [ACT Math Review: 12 Concepts & Strategies You MUST Know For A Perfect 36](https://www.youtube.com/watch?v=cU3Ey6daR8c&t=13s)

5.  [How to use Khan Academy for ACT Math](https://netcollegeprep.com/act-prep-khan-academy/)

6.  [The 3-PASS ACT MATH STRATEGY](https://www.youtube.com/watch?v=i3QcEQ7_2Wk)

Math is a knowledge/ skills heavy section. The timing is quite tough but you can use strategy to strategically skip questions. Any strategy is designed to make sure you have time to get to the questions you can answer and guess on the ones you don't know how to do. The startutors three pass strategy works this way ([The 3-PASS ACT MATH STRATEGY](https://www.youtube.com/watch?v=i3QcEQ7_2Wk))

To prepare, one approach would be to use the [Reason Prep ACT-Math-Gauntlet](https://www.scribd.com/document/412819316/ACT-Math-Gauntlet) to improve your knowledge. You should treat this third party material as a open book test. Anything you don't know look up using Khan Academy or [ACT Math Prep Playlist](https://www.youtube.com/playlist?list=PL2ix4u6yN0jJJGYr0zQVsXY0JozcIDWP9). This should give you a good baseline knowledge to get a score up to a 30. Supplement this with timed practice tests going through areas you don't know or have forgotten. Beyond that use [ACT Math Review: 12 Concepts & Strategies You MUST Know For A Perfect 36](https://www.youtube.com/watch?v=cU3Ey6daR8c&t=13s) for some advanced concepts needed to get towards a 36.

### Reading

1.  [IMPROVE Your ACT READING Score \-- FAST! The 4 Strategy Levels to DOMINATE the ACT Reading Section](https://www.youtube.com/watch?v=-Q5ZW0EK25w)

2.  [I Improved 15 Points with These ACT Reading Strategies \| Updated for the NEW 2022 ACT Reading Test](https://www.youtube.com/watch?v=L2KC738sEvI)

3.  [How To Get A PERFECT Score On The ACT® Reading Section!!](https://www.youtube.com/watch?v=_O1T_J3lDbA)

No real content has to be learned for reading. The difficulty is getting used to the timing and coming up with a strategy to maximize your score. The links above provide different strategies to try. Don't be surprised if it takes many practice tests to improve. Depending on your target score you might be able to guess on one passage or part of the dual passage. It could take 10 or more practice tests (thinking carefully how to improve) to reach your potential.

## Science

1.  [The Ultimate ACT Science Guide (Webinar Edition)](https://www.youtube.com/playlist?list=PLOpq-R2ygzqm3ixThIVr4mRxpC3Zga1Kg)

2.  [ACT Test explanations from the author of the Master Key](https://masterkeyactsat.com/act-videos/act-science/)

3.  [Star Tutors ACT Science Tips, Strategies, and the Unique 3-Pass Method](https://www.youtube.com/watch?v=WEYj7KDazvk)

Surprising science is also not content based. The main skill is the ability to interpret write ups of scientific experiments and articles. Time is also very tight. Like the reading it is more skill based and using practice tests to come up with the best strategy is the best approach. Again you might need to do 10 or more timed practice tests to find the best strategy. Strategies are based on getting to the questions you can get right and potentially guessing on the ones you are not sure. [The Ultimate ACT Science Guide (Webinar Edition)](https://www.youtube.com/playlist?list=PLOpq-R2ygzqm3ixThIVr4mRxpC3Zga1Kg) is a great free resource and a good starting point to form a strategy. [ACT Test explanations from the author of the Master Key](https://masterkeyactsat.com/act-videos/act-science/) provides video answers of a number of recent tests using the strategies described in the accompanying book.
