---
title: "ACT Resources"
editor: visual
---

## Free ACT Resources

### Overall (Free)

1.  [List of every ACT test](https://mcelroytutoring.com/lower.php?url=44-official-sat-pdfs-and-82-official-act-pdf-practice-tests-free)

2.  [Every ACT answer key](https://www.prepsharp.com/act-answer-keys/)

3.  [Brilliant Prep Your-sat-act-study-plan](https://learn.brilliantprep.com/p/your-sat-act-study-plan)

4.  [mcelroy  tutoring ACT action plan](https://www.mcelroytutoring.com/blog-post.php?id=1402&title=ACT+Action+Plan%3A+How+to+Study+and+Prepare+for+the+ACT+College+Entrance+Exam)

### English (Free)

1.  <https://blog.prepscholar.com/the-complete-guide-to-act-grammar-rules>

2.  [Free Virtual ACT English Lesson \-- Covering the Most Important ACT English Grammar Concepts!](https://www.youtube.com/watch?v=aG1iEjVZyZY)

3.  <https://thecriticalreader.com/complete-sat-grammar-rules/>

###  Math (Free)

1.  [The 52 ACT Math Skills](https://www.youtube.com/playlist?list=PL2AoJMrlAorzqxnsyxAyCrtPjYpTdUiTt)

2.  [Reason Prep ACT-Math-Gauntlet](https://www.scribd.com/document/412819316/ACT-Math-Gauntlet)

3.  [ACT Math Prep Playlist](https://www.youtube.com/playlist?list=PL2ix4u6yN0jJJGYr0zQVsXY0JozcIDWP9)

4.  [ACT Math Review: 12 Concepts & Strategies You MUST Know For A Perfect 36](https://www.youtube.com/watch?v=cU3Ey6daR8c&t=13s)

5.  [How to use Khan Academy for ACT Math](https://netcollegeprep.com/act-prep-khan-academy/)

### Reading (Free)

1.  [IMPROVE Your ACT READING Score \-- FAST! The 4 Strategy Levels to DOMINATE the ACT Reading Section](https://www.youtube.com/watch?v=-Q5ZW0EK25w)

2.  [I Improved 15 Points with These ACT Reading Strategies \| Updated for the NEW 2022 ACT Reading Test](https://www.youtube.com/watch?v=L2KC738sEvI)

3.  [How To Get A PERFECT Score On The ACT® Reading Section!!](https://www.youtube.com/watch?v=_O1T_J3lDbA)

## Science (Free)

1.  [The Ultimate ACT Science Guide (Webinar Edition)](https://www.youtube.com/playlist?list=PLOpq-R2ygzqm3ixThIVr4mRxpC3Zga1Kg)

2.  [ACT Test explanations from the author of the Master Key](https://masterkeyactsat.com/act-videos/act-science/)

3.  [Star Tutors ACT Science Tips, Strategies, and the Unique 3-Pass Method](https://www.youtube.com/watch?v=WEYj7KDazvk)
