---
title: "ACT Resources Paid"
editor: visual
---

### Overall

1.  [Official ACT Prep Guide 2023-2024 (AKA the redbook)](https://www.amazon.com/Official-ACT-Prep-Guide-2023-2024/dp/1394196504)

-   The argument for getting this books is to have 6 printed tests all in one place. Potentially you can find these tests online and print them yourself, but the books has answers, answer explanations and bubble sheets. Below are the test codes if you want to find versions online and print them yourself.

-   Test 1: (NEW!) (diagnostic): Dec 2021 E23 (Code 23MC1) all sections (previously not in online module or books)\
    Test 2: June 2017 Code 74C (Code 18MC4), all sections (Test 3 in 2022-2023 book)\
    Test 3: Dec 2017 Code A10 (Code 19MC5), all sections (Test 4 in 2022-2023 book)\
    Test 4: June 2018 Code A11 (Code 20MC6) (test 5 in 2022-2023 book)\
    Test 5: July 2020 Code C01 (Code 20MC8), all sections (test 6 in 2022-2023 book)\
    Test 6: Dec 2019 Code C03 (Code 22MC9) - (Test #1 in 2022-2023 book)

### English

1.  [The Complete Guide to ACT English By Erica Meltzer](https://www.amazon.com/Complete-Guide-ACT-English-Fourth/dp/1733589546/ref=sr_1_7?crid=OYRN4FF0LAKB&keywords=erica+meltzer&qid=1687315662&s=books&sprefix=Erica+%2Cstripbooks%2C104&sr=1-7)

Many people argue the Meltzer book is the best book for ACT English. It covers all of the rules with exercises.

### Math

1.  [Math On The Fly ACT Book](https://www.mathonthefly.com/act-book/) (from the basics to 30+ score)

2.  [Improve your ACT Math score (Udemy should be around \$10-15)](https://www.udemy.com/course/improveyouractmathscore/)

3.  [The Best ACT Math Books Ever](https://supertutortv.com/books/) (Good books if you are looking for a really high score 34+)

4.  [PrepPros: The Complete Guide to ACT Math: The Best Resource to Master ACT Math](https://www.amazon.com/PrepPros-Complete-Guide-Resource-Master/dp/1737183811) (Good book if you are aiming for really high score 34+)

The free resources would and practice exams would cover everything to get a 30+ on the ACT math section. For example, going through the [Reason Prep ACT-Math-Gauntlet](https://www.scribd.com/document/412819316/ACT-Math-Gauntlet) would cover most of the topics you need (core and advanced/30+ topics). However, you would need to use other resources to work out the questions you cannot do. Preppros [ACT Math Review: 12 Concepts & Strategies You MUST Know For A Perfect 36](https://www.youtube.com/watch?v=cU3Ey6daR8c&t=13s) covers many advanced topics

If you want a book that covers this in one place then [Math On The Fly ACT Book](https://www.mathonthefly.com/act-book/) is good. It covers all the basic topics well. It explains every topic really well and is set-up for self study. There are also lots of exercises. It also covers many of the 30+ topics so you can fill in gaps on topics that you might not have covered. [Improve your ACT Math score ](https://www.udemy.com/course/improveyouractmathscore/) is also a good alternative if you are a visual learner. The course has some focus on maximizing the use of a TI84 calculator (e.g. matricies, complex numbers, using graph to solve certain problems). The course also focuses on problems from real ACT exams

The final two books really cover almost everything in great depth. If you are scoring a 32/33 on practice tests and need more these books could take you further. They are written by tutors (Supertutor and preppros) and also have video courses associated with them

### Reading

Currently I don't have a strong recommendation or experience of paid resources for reading. Various strategies and tips can be gathered in the free resources.

### Science

1.  [MASTER KEY ACT SCIENCE crystal clear guide](https://www.amazon.com/MASTER-KEY-ACT-SCIENCE-crystal-clear/dp/1796625841)

The free resources would probably be enough to crack the ACT science section. However, if you want a book that covers every type of question along with a technique to answer the question, then the Master Key is this book.
