---
title: "The Plan"
editor: visual
---

### The Baseline Test

Before starting prep you need to take a test under exam conditions, so that you can monitor improvement.

Take test Dec 2021 E23 (Code 23MC1). This is the redbook diagnostic test.

Use the prepsharp virtual proctor ([link](https://www.prepsharp.com/act-test-timers/)) to keep to the proper time and incorporate the required breaks

### English round 1

-   Check answers from baseline test, score, & record in Log

-   Review right & wrong answers in detail

    It is *necessary* that every single time you get something wrong, REVIEW the mistake. If you don't get why you got it wrong, check back on the guide (<https://blog.prepscholar.com/the-complete-guide-to-act-grammar-rules>). Remember, the ACT English section is NOT AT ALL subjective---if you follow the rules you should get a 36.

-   Watch [ACT English Grammar Rules!](https://www.youtube.com/watch?v=lFqfD-A4Nts)

-   Complete a timed practice test English Test 2: June 2017 Code 74C (Code 18MC4)

-   Check answers & record in Log

-   Review right & wrong answers in detail (<https://blog.prepscholar.com/the-complete-guide-to-act-grammar-rules>) also use redbook if you have it.

-   Complete a timed practice test English Test 3: Test 3: Dec 2017 Code A10

-   Check answers from baseline test, score, & record in Log

-   Review right & wrong answers in detail (<https://blog.prepscholar.com/the-complete-guide-to-act-grammar-rules>) also use redbook if you have it.

### Math round 1

-   Check answers from baseline test, score, & record in Log

-   Review right & wrong answers in detail using the redbook or [ACT Math E23](https://www.youtube.com/playlist?list=PL_tX83dUzqlh7MDFe1LI2Uc-SOLcp5yGA)

-   Review [The 3-PASS ACT MATH STRATEGY](https://www.youtube.com/watch?v=i3QcEQ7_2Wk) and use this in subsequent timed practice tests

-   Review [New ACT Calculator Strategies UPDATED](https://www.youtube.com/watch?v=tY1uMGMMQgg&t=297s)

-   Open book: complete odd number problems (1-140) in the math Gauntlet ([Register for free download ACT Math Gaunlet](https://learn.brilliantprep.com/p/the-vault-sat-act-downloads)). Potentially use [ACT Math Prep Playlist](https://www.youtube.com/playlist?list=PL2ix4u6yN0jJJGYr0zQVsXY0JozcIDWP9) to help with topics you are struggling with

-   Complete a timed practice test Math Test 2: June 2017 Code 74C (Code 18MC4)

-   Check answers & record in Log

-   Review right & wrong answers in detail using the redbook or https://www.cambridgeed.com/wp-content/uploads/2020/10/ACT-18MC4-Navigator.pdf

-   Open book: complete even number problems (1-140) in the math Gauntlet ([Register for free download ACT Math Gaunlet](https://learn.brilliantprep.com/p/the-vault-sat-act-downloads)). Potentially use Khan academy or [ACT Math Prep Playlist](https://www.youtube.com/playlist?list=PL2ix4u6yN0jJJGYr0zQVsXY0JozcIDWP9) to help with topics you are struggling with.

-   Complete a timed practice test Math Test 3: Test 3: Dec 2017 Code A10

-   Check answers & record in Log

-   Review right & wrong answers in detail using the redbook

### Reading round 1

-   Check answers from baseline test, score, & record in Log

-   Review right & wrong answers in detail

-   Look at the following strategy and links:

    1.  [IMPROVE Your ACT READING Score \-- FAST! The 4 Strategy Levels to DOMINATE the ACT Reading Section](https://www.youtube.com/watch?v=-Q5ZW0EK25w)

    2.  [The BEST ACT® Reading Strategies and Tricks that Helped Me Improve 15 Points ](https://www.youtube.com/watch?v=-m5xCdMxyvE&list=PL2AoJMrlAoryYObds-OBUhqc2bSfnCUfj&index=2)

    3.  [How To Get A PERFECT Score On The ACT® Reading Section!!](https://www.youtube.com/watch?v=_O1T_J3lDbA)

-   Select a strategy and Complete a timed practice test Reading Test 2: June 2017 Code 74C (Code 18MC4)

-   Check answers, score, & record in Log

-   Review right & wrong answers in detail

-   Complete a timed practice test reading Test 3: Test 3: Dec 2017 Code A10

-   Check answers, score, & record in Log

### Science round 1

-   Check answers from baseline test, score, & record in Log

-   Review right & wrong answers in detail

-   Review [The Ultimate ACT Science Guide (Webinar Edition)](https://www.youtube.com/playlist?list=PLOpq-R2ygzqm3ixThIVr4mRxpC3Zga1Kg)

-   Review [Top ACT Science Tips/Strategies - Managing Time Well](https://www.youtube.com/watch?v=pv5hOBYP-l0)

-   Complete a timed practice test Science Test 2: June 2017 Code 74C (Code 18MC4)

-   Check answers, score, & record in Log

-   Review right & wrong answers in detail

-   Complete a timed practice test reading Test 3: Test 3: Dec 2017 Code A10

-   Check answers, score, & record in Log

-   Review right & wrong answers in detail

### Full test 2

-   Take Test 4: June 2018 Code A11 (Code 20MC6) (test 5 in 2022-2023 book)

-   Check answers from baseline test, score, & record in Log

-   Review right & wrong answers in detail

### Round 2 

-   Round 2 proceeds similar to round 1 using Test 5: July 2020 Code C01 (Code 20MC8) and Test 6: Dec 2019 Code C03 (Code 22MC9) from the red book for the timed section practice tests

-   For English you could potentially use [The Complete Guide to ACT English By Erica Meltzer](https://www.amazon.com/Complete-Guide-ACT-English-Fourth/dp/1733589546/ref=sr_1_7?crid=OYRN4FF0LAKB&keywords=erica+meltzer&qid=1687315662&s=books&sprefix=Erica+%2Cstripbooks%2C104&sr=1-7) if you need extra exercises or review of certain topics.

-   For **Math**, complete math Gauntlet advanced problems (open book) and review [ACT Math Review: 12 Concepts & Strategies You MUST Know For A Perfect 36](https://www.youtube.com/watch?v=cU3Ey6daR8c&t=13s). Potentially use [Math On The Fly ACT Book](https://www.mathonthefly.com/act-book/) for review of certain topics

-   For **Science and Reading,** you might need extra practice tests to fine tune timing strategies. Use the tests in [ACT Test explanations from the author of the Master Key](https://masterkeyactsat.com/act-videos/act-science/). This has the added benefit that you can use the video solutions for the scienceFinal Practice test

### The Final Practice Test

-   Take a final practice test [ACT official practice test form 2176CPRE](https://www.act.org/content/dam/act/unsecured/documents/Preparing-for-the-ACT.pdf)

-   Check answers, score, & record in Log

-   Review right & wrong answers in detail
